import type { MissionConfig, Settings, Subsystem } from '@/types';

/** Missão padrão usada na primeira execução (antes de qualquer edição). */
export const defaultMission: MissionConfig = {
  name: 'Exploração de Marte',
  code: 'ARES-IX',
  commander: 'Cmd. A. Ramos',
  crewSize: 4,
  launchDate: '2026-09-14',
  targetOrbitKm: 420,
};

export const defaultSettings: Settings = {
  autoRefresh: true,
  refreshIntervalSec: 3,
  alertsEnabled: true,
};

/**
 * Subsistemas padrão com métricas e faixas de operação.
 * Os limites warn/crit definem quando os alertas automáticos disparam.
 */
export const defaultSubsystems: Subsystem[] = [
  {
    key: 'sensors',
    label: 'Sensores',
    icon: 'thermometer-outline',
    metrics: [
      {
        id: 'cabin_temp',
        label: 'Temp. da Cabine',
        unit: '°C',
        value: 22,
        warnLow: 18,
        warnHigh: 26,
        critLow: 10,
        critHigh: 32,
        min: 0,
        max: 45,
      },
      {
        id: 'pressure',
        label: 'Pressão Interna',
        unit: 'kPa',
        value: 101,
        warnLow: 95,
        warnHigh: 105,
        critLow: 85,
        critHigh: 115,
        min: 70,
        max: 130,
      },
      {
        id: 'radiation',
        label: 'Radiação',
        unit: 'mSv/h',
        value: 0.3,
        warnLow: -1,
        warnHigh: 0.5,
        critLow: -1,
        critHigh: 1.2,
        min: 0,
        max: 2,
      },
    ],
  },
  {
    key: 'energy',
    label: 'Energia',
    icon: 'flash-outline',
    metrics: [
      {
        id: 'battery',
        label: 'Carga da Bateria',
        unit: '%',
        value: 87,
        warnLow: 40,
        warnHigh: 101,
        critLow: 20,
        critHigh: 101,
        min: 0,
        max: 100,
      },
      {
        id: 'solar_output',
        label: 'Saída Solar',
        unit: 'kW',
        value: 9.4,
        warnLow: 6,
        warnHigh: 15,
        critLow: 3,
        critHigh: 18,
        min: 0,
        max: 20,
      },
      {
        id: 'consumption',
        label: 'Consumo',
        unit: 'kW',
        value: 7.1,
        warnLow: -1,
        warnHigh: 11,
        critLow: -1,
        critHigh: 14,
        min: 0,
        max: 18,
      },
    ],
  },
  {
    key: 'communication',
    label: 'Comunicação',
    icon: 'radio-outline',
    metrics: [
      {
        id: 'signal',
        label: 'Força do Sinal',
        unit: 'dBm',
        value: -68,
        warnLow: -90,
        warnHigh: 0,
        critLow: -110,
        critHigh: 0,
        min: -120,
        max: -40,
      },
      {
        id: 'latency',
        label: 'Latência',
        unit: 'ms',
        value: 620,
        warnLow: -1,
        warnHigh: 900,
        critLow: -1,
        critHigh: 1400,
        min: 0,
        max: 2000,
      },
      {
        id: 'packet_loss',
        label: 'Perda de Pacotes',
        unit: '%',
        value: 1.2,
        warnLow: -1,
        warnHigh: 5,
        critLow: -1,
        critHigh: 12,
        min: 0,
        max: 30,
      },
    ],
  },
  {
    key: 'orbital',
    label: 'Estabilidade Orbital',
    icon: 'planet-outline',
    metrics: [
      {
        id: 'altitude',
        label: 'Altitude',
        unit: 'km',
        value: 418,
        warnLow: 400,
        warnHigh: 440,
        critLow: 380,
        critHigh: 460,
        min: 350,
        max: 480,
      },
      {
        id: 'velocity',
        label: 'Velocidade',
        unit: 'km/s',
        value: 7.66,
        warnLow: 7.4,
        warnHigh: 7.9,
        critLow: 7.1,
        critHigh: 8.2,
        min: 6.5,
        max: 8.5,
      },
      {
        id: 'inclination',
        label: 'Inclinação',
        unit: '°',
        value: 51.6,
        warnLow: 50,
        warnHigh: 53,
        critLow: 48,
        critHigh: 55,
        min: 45,
        max: 58,
      },
    ],
  },
];
